Reload messages on /gpreload
GriefPrevention/GriefPrevention pull request #1266
Opened 2021-02-16 16:12 UTC by budi1200

2021-02-16 16:25 UTC, Jikoo requested changes
Overall looks good, definitely a useful change. Couple of style issues and visibility choices I'd argue against, but other than that 👍

2021-02-16 16:25 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/DataStore.java
> +    public void loadMessages()
Should probably be protected, not public.

2021-02-16 16:25 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java
> +			this.dataStore.loadMessages();
This line is indented with tabs, should be spaces.

2021-02-16 16:25 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java
> +    public void resetPattern(){
Opening brace should be on the next line.

2021-02-16 16:25 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java
> +    public void resetPattern(){
Should consider protected here as well.

2021-02-16 16:34 UTC, RoboMWM commented
hmm, guess not all IDEs respect .editorconfig

2021-02-16 16:54 UTC, Jikoo commented
> hmm, guess not all IDEs respect .editorconfig

Yeah, it's an IJ thing, but it's moderately portable.

2021-02-16 16:57 UTC, Jikoo approved these changes
Looks good! Reviewing again to dismiss my old review, you'll need Robo's approval for pulling though.

2022-06-13 16:42 UTC, KayaLambrechts commented
Could this be merged?

2023-03-09 22:40 UTC, RoboMWM approved these changes

2023-03-09 22:45 UTC, merged