Prevent theft from water/lava cauldrons.
GriefPrevention/GriefPrevention pull request #1908
Opened 2022-07-03 08:08 UTC by RezzedUp

I noticed that players are able to take water & lava from claimed cauldrons, but they aren't able to fill them back up. This should prevent players from stealing from claimed cauldrons in the first place. It also prevents untrusted players from washing banners, armor, and shulker boxes (which all reduce water cauldrons 1 level until they're empty).

2022-07-03 20:23 UTC, Jikoo requested changes
If you're adding 1.19 materials to checks, you should bump `api-version` to 1.19. I believe that there's also handling for pre-1.19 cauldrons in the PlayerBucketEvent that should be stripped out, but I haven't checked that.

2022-07-03 21:23 UTC, RezzedUp commented
These materials were introduced in 1.18, so no api-version bump needed here. Anyhow, the only place regarding protecting cauldrons specifically in the entire codebase is inside the modified method (the `PlayerInteractEvent` listener). If the bucket event listeners were meant to stop players from interacting with cauldrons, for one, they don't currently work, and that also wouldn't stop other interactions like filling glass bottles or washing banners/etc.

If you would like a more thorough & conclusive handler for cauldrons, I could add a listener for [CauldronLevelChangeEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/CauldronLevelChangeEvent.html), which also has the benefit of preventing other plugins from updating claimed cauldrons on behalf of players if they send out their own 'permission test' event. In fact, before submitting this PR, [I experimented with that but ultimately scrapped it](https://github.com/TechFortress/GriefPrevention/compare/master...LeafCommunity:GriefPrevention:stale/protect-cauldron-contents) because simply adding the updated material types was a much more straightforward solution to the problem. There are certainly other changes I would make before submitting that listener here (as you can see, this was before I realized cauldrons were considered containers), but it's on the table.

2022-07-03 21:31 UTC, Jikoo commented
Gotcha, don't think 1.18 actually added materials, only the generation for them, so 1.17 should still be sufficient. You're right, there's no additional handling... could have sworn there was something for it, but maybe there's a related issue I'm remembering instead. I think this approach is fine, though you're right that the CauldronLevelChangeEvent is probably the most correct.

2022-07-22 00:14 UTC, RoboMWM approved these changes

2022-07-22 00:16 UTC, RoboMWM commented
Interesting, I'm not able to make changes to update this with the current branch commit huh

2022-07-22 04:16 UTC, RezzedUp commented
It's probably because I'm PRing from an organization - next time I'll PR from my own account instead. I just rebased the branch so it's up to date & in line with master.

2022-07-23 02:23 UTC, RoboMWM commented
I guess it defaults to not allowing edits, but I think even if PRing from an org that should be possible? Idk for sure though, been a while since I've made a PR.

2022-07-23 02:23 UTC, merged