Added permission check for Allays
GriefPrevention/GriefPrevention pull request #1958
Opened 2022-10-19 17:59 UTC by MrButtersDEV

Added a permission check similar to pets for setting what item an allay can pick up.
- There is currently a visual bug when canceling the interaction with an allay.

2022-11-18 19:38 UTC, RoboMWM commented
I've been severely inactive in the Minecraft scene for some time, and I'm trying to understand the effects of this. What risk in regards to grief can one perform via giving/taking items from an allay? My only guess is taking things from an allay displayed cosmetically in a claim?

2022-11-20 22:02 UTC, MrButtersDEV commented
> I've been severely inactive in the Minecraft scene for some time, and I'm trying to understand the effects of this. What risk in regards to grief can one perform via giving/taking items from an allay? My only guess is taking things from an allay displayed cosmetically in a claim?

Some users have come up with ways to use allays in automated farms for item collection and sorting. Others being able to change what item they are holding allows users to disrupt (grief) the intended process.

2022-12-09 17:16 UTC, UsefullSpoon approved these changes
looks good

2022-12-16 15:05 UTC, Jikoo requested changes
Most major thing is the missing `api-version: 1.19` that needs to be included if 1.19 features are used.

I'm semi-reluctant to give this my full seal of approval because while this does fix the easiest way to steal an allay, it does not address luring the allay out by dropping items matching its current, then swapping its item to take ownership. That said, that flaw is somewhat more in line with bees being not completely tracked and protected, users having some level of responsibility to build intelligently.

2022-12-16 15:05 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java
> +    public boolean config_claims_protectAllays;                     //weather allays on a claim should be protected by that claim's rules
Spelling

2022-12-16 15:05 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java
> +
Extra whitespace

2022-12-16 15:05 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java
> +            if (entity instanceof Allay) //check if player tried to set item
While there aren't currently any Tameable Allay implementations that I'm aware of, it would be better to not have this in an else following the section for Tameable handling. It's similar to how armor stands are handled below.

2022-12-16 15:05 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java
> +                    Supplier<String> override = () ->
This override message is duplicate code and should be removed. It matches the supplier that would be constructed for `ClaimPermission.Inventory` by default. You only need an override if you want to use a different message, i.e. how interacting with claimed entities generally uses `Messages.NoDamageClaimedEntity` instead.

See https://github.com/TechFortress/GriefPrevention/blob/058ae98ceea307cf72155bde421564080ac85eb1/src/main/java/me/ryanhamshire/GriefPrevention/Claim.java#L587-L594 and https://github.com/TechFortress/GriefPrevention/blob/058ae98ceea307cf72155bde421564080ac85eb1/src/main/java/me/ryanhamshire/GriefPrevention/ClaimPermission.java#L37

2023-12-20 10:57 UTC, SenorFlamingo commented
Is this pull request still alive? We have a problem on our server with allays, anyone can steal the items from them even in claimed area

2024-01-05 20:34 UTC, RoboMWM commented
The PR owner appears to have not followed up on the review left by Jikoo.

2024-03-29 11:21 UTC, snurre0 commented
@MrButtersDEV Would it be possible for you to follow up on the review here? 🙂

2024-04-01 07:16 UTC, SenorFlamingo commented
PR owner looks inactive for over half a year, not sure if he comes back for this

2024-04-01 15:05 UTC, Jikoo commented
> PR owner looks inactive for over half a year, not sure if he comes back for this

Their last GitHub-tracked activity was Mar 28 in a private repo, 3 days ago. I wouldn't be surprised to not see them bother due to the PR age, but they're definitely active.

2026-02-05 17:46 UTC, RoboMWM commented
New, cleaner PR: https://github.com/GriefPrevention/GriefPrevention/pull/2558

2026-02-05 17:46 UTC, closed without merging