Remove `TheUnderground` from softdepend
GriefPrevention/GriefPrevention pull request #2010
Opened 2023-02-19 21:22 UTC by bigpresh

See rationale on issue #2009, in particular https://github.com/TechFortress/GriefPrevention/issues/2009#issuecomment-1436095403

... but recent changes to Paper in https://github.com/PaperMC/Paper/pull/8108 have caused a circular dependency error to be triggered by this - we (soft-!)depend on `TheUnderground`, which depends on GriefPrevention, and boom.  I'd argue that a softdepend should not be considered a circular dependency really, but it is, currently, and results in an error like:

```
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies detected!
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] You have a plugin that is depending on a plugin which refers back to that plugin. Your server will shut down until these are resolved, or the strategy is changed.
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies:
[11:26:57 ERROR]: [ConfiguredOrderedProviderStorage] GriefPrevention depends on TheUnderground depends on GriefPrevention...
```

`TheUnderground` appears to only work on 1.10, and current GriefPrevention builds don't support anything that ancient, so there doesn't seem to be much point in maintaining it in the softdepends list.  It also doesn't look widely used anyway.

Note that it was already removed from `loadbefore` in 6d0a1b9

2023-02-19 21:28 UTC, Owen1212055 requested changes
This was already fixed by me in https://github.com/TechFortress/GriefPrevention/pull/1912

The issue is that the plugin author has not released an update.

2023-02-19 21:47 UTC, bigpresh commented
> This was already fixed by me in https://github.com/TechFortress/GriefPrevention/pull/1912

Ahh, thank you - it wasn't clear to me that removing it from loadbefore would solve the circular dep issue.  Thanks for your explanation on that PR on softdepend vs loadbefore.

I'll leave this PR open for now for opinions from @RoboMWM et al, as I still think it sounds sensible to entirely remove TheUnderground, as a closed-source plugin that as far as I can tell only works with older MC versions.

2023-02-20 17:47 UTC, RoboMWM commented
I've only left it there because I've never looked into that plugin nor seen if it's needed for anything. If it is indeed out of date and not usable/being used, then I'll drop it completely. No need to softdepend on something this plugin does not use, though I guess that applies to a lot of the plugins listed in there anyway...

I wonder if there's a way to design the plugin to not need to softdepend. Maybe loading claims on ServerLoadFinishedEvent or whatever it's called.

2023-02-20 17:51 UTC, RoboMWM approved these changes

2023-02-20 17:52 UTC, merged

2023-03-14 14:36 UTC, c0wg0d commented
I was a huge fan of TheUnderground.  It probably had softdepend support because it generated a new world.  It was made by minelazz, who is the author of EpicWorldGenerator and EpicNetherGenerator.