Adds /creaturetrust command and removes killing of mobs being from container trust.
GriefPrevention/GriefPrevention pull request #2031
Opened 2023-04-02 06:51 UTC by Skizzles

Adds /creaturetrust command, along with messages, database storage for it, and adds it to all other areas. This separates killing of mobs from the containertrust permission.

This is compatible with old installations and has been tested as working, if players use the new command the information is automatically added and updated accordingly with their claim.

Feel free to let me know if I am missing something or need to change something!

2023-04-09 02:24 UTC, RoboMWM commented
I appreciate the PR, however, I prefer to keep the trust system as simple as possible. I know I've been slow on refactoring for a better API, but extra trust levels is something I also want to give out to addons, so addons can implement permissions in any way they choose (be it extra trust levels, or even more granular with flags, etc.)

2023-04-09 06:00 UTC, Skizzles commented
> I appreciate the PR, however, I prefer to keep the trust system as simple as possible. I know I've been slow on refactoring for a better API, but extra trust levels is something I also want to give out to addons, so addons can implement permissions in any way they choose (be it extra trust levels, or even more granular with flags, etc.)

While I understand keeping things simple, the current permissions being how they are open players up to grief by forcing them to allow container trust, making it required to have a secondary plugin to protect containers. I created this so players could also have public areas for grinders which was not possible with the current setup. All other config options, commands, etc opened players up to grief or having other animals killed.

If examples of necessity or more opinions would get this PR merged I can gather that, but I truly believe this would be a great addition in the meantime before an addon system and API in a stable place.

2023-04-09 13:32 UTC, Jikoo requested changes
This is not compatible with existing installations, potentially incompatible with addons depending on which methods they use, and the database datastore is broken. See review comments for specifics.

As far as personal reservations go, this adds confusing complexity. Most of the requests I've seen for creature trust are for allowing only access to animals, i.e. milking cows and shearing sheep and not killing, so I believe most users would expect that to be what this is. GP's linear trust model makes it difficult for specific behavioral changes like that to be conveyed to users, especially once addons get involved. I believe in GP's current state this is best entirely left to an addon rather than partially because it will reduce player confusion from server to server.
> the current permissions being how they are open players up to grief by forcing them to allow container trust, making it required to have a secondary plugin to protect containers. I created this so players could also have public areas for grinders which was not possible with the current setup.

Create a subclaim around the pen/kill zone and only containertrust people inside it. They won't be able to access the storage chests in the rest of the claim, but they will be able to kill things. Bonus points if you allow them to use a lever to disable hoppers in the grinder so they can pick up loot instead of having it go into a sorting system.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/FlatFileDataStore.java
> +                        line = inStream.readLine();
This is the sixth line (not fifth, as the copied comment indicates), which is already used for access trust data. This unexpectedly elevates permissions for users.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/FlatFileDataStore.java
> +                        creatureNames = this.convertNameListToUUIDList(creatureNames);
Name list should already be a UUID list - this conversion is for legacy data. Doesn't need to be done.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java
> +            statement.execute("CREATE TABLE IF NOT EXISTS griefprevention_claimdata (id INTEGER, owner VARCHAR(50), lessercorner VARCHAR(100), greatercorner VARCHAR(100), builders TEXT, containers TE
`creatures, TEXT` -> `creatures TEXT`

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java
> +            "INSERT INTO griefprevention_claimdata (id, owner, lessercorner, greatercorner, builders, containers, creatures, accessors, managers, inheritnothing, parentid) VALUES (?, ?, ?, ?, ?, ?, ?
Missing corresponding new VALUES entry.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +    Claim(Location lesserBoundaryCorner, Location greaterBoundaryCorner, UUID ownerID, List<String> builderIDs, List<String> containerIDs, List<String> creatureIDs, List<String> accessorIDs, List<Str
Needs an overload to not break existing addons using this constructor.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +    Claim(Location lesserBoundaryCorner, Location greaterBoundaryCorner, UUID ownerID, List<String> builderIDs, List<String> containerIDs, List<String> creatureIDs, List<String> accessorIDs, List<Str
Needs an overload.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +    public void getPermissions(ArrayList<String> builders, ArrayList<String> containers, ArrayList<String> creatures, ArrayList<String> accessors, ArrayList<String> managers)
Needs an overload.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/ClaimPermission.java
> +     */
Comment is beneath the enum value, which was also inserted beneath the access trust comment.

2023-04-09 13:32 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java
> +                creaturesNames = this.convertNameListToUUIDList(creaturesNames);
Name list should already be a UUID list - this conversion is for legacy data. Doesn't need to be done.

2023-04-15 13:43 UTC, Jikoo requested changes

2023-04-15 13:43 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/FlatFileDataStore.java
> +                        line = inStream.readLine();
You didn't actually resolve the problems here by correcting the line number comments. This elevates existing access trust and converts existing permission trust into access trust. A new type of trust should be the last line. You cannot insert it into the middle without providing a converter for existing data.

2023-06-18 03:39 UTC, RoboMWM commented
I understand there is a need for more granular permission tiers on some servers - and as such, I'd be more preferential to PRs that help refactor/add API capabilities to this if it is not already possible.

2023-06-18 03:39 UTC, closed without merging