Create ClaimCreateEvent.java
GriefPrevention/GriefPrevention pull request #211
Opened 2017-09-10 18:03 UTC by Miclebrick

This allows other plugins to cancel the creation of claims.

2017-09-10 18:38 UTC, bigpresh commented
I think the commit 1660d001ab80a3e0b1180ef1b688d9f192af0f12 in PR #212 should be added to this PR, as it's one logical discrete changeset - the other PR is no use without this one - but at a quick glance, it looks good and sane, and will be useful for other plugins to be able to block claim creations if they don't meet some additional criteria, etc.

2017-09-10 22:16 UTC, RoboMWM commented
Should note/add a warning that this will be called for claim resizes as well; which is part of the reason why I'm focusing on version 20.

2017-09-10 22:20 UTC, RoboMWM requested changes
Also add your other commit from the other PR as bigpresh mentioned.

2017-09-10 22:20 UTC, RoboMWM commented on src/me/ryanhamshire/GriefPrevention/events/ClaimCreateEvent.java
> +public class ClaimCreatedEvent extends Event implements Cancellable {
Doesn't match file name, so this doesn't compile (see Travis log)

Probably would be a good idea to see if it compiles before submitting ¯\\\_(ツ)\_/¯

2018-06-12 06:12 UTC, RoboMWM commented
imma assume ur never gonna fix dis

2018-06-12 06:12 UTC, closed without merging