Restructure project to maven standard
GriefPrevention/GriefPrevention pull request #270
Opened 2018-03-16 00:47 UTC by Narimm

Firstly there are NO code changes in this commit - it is strictly a restructure.  It brings the repository into a maven standard. Stripping support files out of the source code and moving them the correct directory structure to ensure readability going forward.

- Move tests to the correct directory
- Create resources and move them to the correct directory
- Create .github and move templates.
- Add a default encoding to ensure cross platform building is consistent.

2018-03-16 04:37 UTC, RoboMWM commented on pom.xml
> +                <targetPath>.</targetPath>
targetPath is for..?

2018-03-16 04:39 UTC, RoboMWM commented
Seems okay, though this is something that's already done in version 20. But I guess since there's really no open PRs that are ready to be merged (with exception of the hyperconomy one I suppose, which is only a single line anyways), I guess this is okay. I'll pull when I have time to just double check things over.

2018-03-16 10:11 UTC, Narimm commented
<targetpath> definitively defines where you want resources to end up in the jar...
rather than relying on default.

2018-03-19 00:54 UTC, Narimm commented
@RoboMWM where is version 20?

2018-03-19 05:46 UTC, RoboMWM commented
#63

2018-05-04 20:25 UTC, RoboMWM requested changes
So for some of these not sure what happened, if you changed line endings or something? Unsure if you can somehow make it so all files are just a move instead of some files having a random full delete and insert; otherwise looks good.

2018-06-12 06:05 UTC, Narimm commented
Ok so I updated the branch and fixed the stupid line ending changes that intellij must make...I had to use git cmd line ....but its done!!!!

2018-06-12 06:08 UTC, Narimm commented
RobMWM,  mananged to get the moves done without the silly LF changes (I think it was line ending s that cause the problem earlier

2018-06-12 06:08 UTC, RoboMWM approved these changes

2018-06-12 06:09 UTC, RoboMWM commented
Yay, much cleaner diff c:

2018-06-12 06:11 UTC, merged