Claim modified event cancellable
GriefPrevention/GriefPrevention pull request #405
Opened 2018-11-03 02:08 UTC by 112madgamer

Allow the event to be cancelled on request of #383

2018-11-03 03:58 UTC, RoboMWM submitted a review, later dismissed
Looks like good progress otherwise. Still needs to act upon this cancel status.

2018-11-03 03:58 UTC, RoboMWM commented on src/main/java/me/ryanhamshire/GriefPrevention/events/ClaimModifiedEvent.java
> +//Allow the event to be cancelled //112madgamer
Unnecessary comment, and in the wrong place anyways.

Please remove.

2018-11-03 04:33 UTC, RoboMWM requested changes
Looks good, but the plugin needs to check cancel status and cancel modification if this event is canceled. Idk how easy that'll be.

2020-09-13 14:22 UTC, Jikoo commented
Implemented by #942

2020-09-13 14:22 UTC, closed without merging