Expose playerIDToClaimPermissionMap
GriefPrevention/GriefPrevention pull request #757
Opened 2020-03-24 03:51 UTC by LogGits

I could use this to resolve #756

2020-03-24 13:08 UTC, Jikoo commented
Not a fan of directly supplying mutable fields, would much prefer to see this class get locked down more, providing setters and getters instead.
Should instead consider exposing `Claim#hasExplicitPermission`. Alternately, you can use `Claim#getPermissions` to check to see if your user's data is present.

What's the end goal with an explicit check instead of a check that includes public build access?

2020-03-25 00:26 UTC, LogGits commented
let me know if any other changes are needed 👍

2020-03-25 00:53 UTC, RoboMWM requested changes
I'm still trying to understand the use case - what are you trying to do, and how does the existing API fail to meet your needs?

2020-03-25 00:53 UTC, RoboMWM commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +	public void setClaimPermissionMap (HashMap<String, ClaimPermission> claimPermissionMap) {
Two questions:
1. Is there any reason why we'd want this to be mutable in this fashion?
2. I would instead have something for adding to the existing map instead of just taking in a random map that could screw up the claim and how it's saved

Also note that anything that uses this will also have to ensure the claim gets saved as well. So I highly recommend not having this here.

2020-03-25 01:04 UTC, LogGits commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +	public void setClaimPermissionMap (HashMap<String, ClaimPermission> claimPermissionMap) {
> I'm still trying to understand the use case - what are you trying to do, and how does the existing API fail to meet your needs?

I am trying to check if an OfflinePlayer has any type of ClaimPermission in a simple matter. Trying to avoid using 4 seperate lists to check if their uuid exists. Opening this map would save me unnecessary code. 
I'd also recommend having something like for single claimPermission type checks:
```java
//Allows retrieving lists of users who have the specified claim permissionType.
public List<String> getPermissions (ClaimPermission permissionType) {
    List<String> list = new ArrayList();
    this.playerIDToClaimPermissionMap.forEach((key, value) -> {
        if (value == permissionType) list.add(key);
    });
    return list;
}
```

If you'd like i can remove the setter (I don't need it only added as per Jikoo's request) and add this new getPermissions version aswell. let me know 🙂

2020-03-25 01:07 UTC, Jikoo commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +	public void setClaimPermissionMap (HashMap<String, ClaimPermission> claimPermissionMap) {
Like I said, why not just change `Claim#hasExplicitPermission` to have public access?

Also, you keep not answering what your actual use case is. We understand what you're trying to do, but we want to know why. Without knowing what your end goal is, we can't offer a better solution.

2020-03-25 01:40 UTC, LogGits commented on src/main/java/me/ryanhamshire/GriefPrevention/Claim.java
> +	public void setClaimPermissionMap (HashMap<String, ClaimPermission> claimPermissionMap) {
> Like I said, why not just change `Claim#hasExplicitPermission` to have public access?

`hasExplicitPermission (Player player, ClaimPermission level)`
Setting it to public would still not allow me to do what i am trying to achieve.

> We understand what you're trying to do, but we want to know why.

I am storing uuid data on a sign. Im using it to prevent exploiting a system that allows claim trustees to share containers. e.g. player owns a container in trusted space. If player is in the claim then all other claim members can access it. The abuse im trying to avoid is if a player just removes that player they will still have access to the shared containers. Hence, I am trying to check they are in the same claim using the `playerIDToClaimPermissionMap` but it's privated. Hence, i created the getter so i can easily check this.

2020-03-25 01:44 UTC, LogGits commented
> We understand what you're trying to do, but we want to know why.

I am storing uuid data on a sign. Im using it to prevent exploiting a system that allows claim trustees to share containers. e.g. player owns a container in trusted space. If player is in the claim then all other claim members can access it. The abuse im trying to avoid is if a player just removes that player they will still have access to the shared containers. Hence, I am trying to check they are in the same claim using the `playerIDToClaimPermissionMap` but it's privated. Therefore, i created the getter so i can easily check this.

2020-03-25 16:01 UTC, RoboMWM commented
I'm still not sure what's going on. Are you implementing your own form of container permissions? It seems it has a very weird relationship with claim permissions...

Functionality wise, it sounds like we need to support OfflinePlayer lookups - I know it's used elsewhere for player matching.

2020-03-25 16:41 UTC, Jikoo commented
>The abuse im trying to avoid is if a player just removes that player they will still have access to the shared containers. Hence, I am trying to check they are in the same claim using the playerIDToClaimPermissionMap but it's privated. Therefore, i created the getter so i can easily check this.

But as long as the player still has access to containers by any means, including public container trust, they can still open their container. I don't see how this changes anything from the player's perspective. Explicit individual trust would not allow them any greater level of access.

I do think that for addons it may be useful to provide a way to add custom permitted data similar to how the permission check currently works, but I don't think your use case requires anything more than the current API.

If your reluctance to use the provided methods revolves around their performance (I'll admit, I'm not exactly thrilled with how the checks are run) then maybe you could improve that instead of bypassing them.

2020-03-25 23:45 UTC, LogGits commented
> I'm still not sure what's going on. Are you implementing your own form of container permissions? It seems it has a very weird relationship with claim permissions...

@RoboMWM Essentially yes something like lockette. Prevents access but also allows sharing containers in claims (optional).

v20 has the ability to access the trustee map:
https://github.com/TechFortress/GriefPrevention/blob/d5638e7694079bf385aa9258b58a93013a65c69b/src/main/java/me/ryanhamshire/GriefPrevention/claim/Claim.java#L60

I don't follow what it's being suggested. What have I done here that doesn't benefit the project. The ability to access claim permission data easily allowing for custom handling of things like explicit permission calculation is pretty important.

2020-03-26 04:06 UTC, RoboMWM commented
v20 stuff hasn't had any decisions made, all public stuff is subject to change.

> I don't follow what it's being suggested. What have I done here that doesn't benefit the project.

We're just trying to understand what's being done and why the API at its current state doesn't allow for what you want to do. My understanding was that the API is sufficient for checking containertrust; i.e., I'd rather solve the underlying issue instead of just adding a "quick fix."

2020-03-28 00:29 UTC, LogGits commented
> My understanding was that the API is sufficient for checking containertrust; i.e., I'd rather solve the underlying issue instead of just adding a "quick fix."

This is not a quick fix. This is an addition that will help developers in the long run allowing them to easily gather ClaimPermission data from a claim. The addition has nothing to do with container trust, i'd be checking build trust, which still is just my usage and doesn't necessarily limit this addition at all. The addition was made as a broad method to gather ClaimPermission info from a claim. In this case i'd be checking that an OfflinePlayer (via uuid) has access to a claim. The current api isn't sufficient because all current methods either require an online player or require unnecessary list creations (the current getPermissions()). In this PR I am adding a way to access the ClaimPermission HashMap (without being able to modify it (even though people should be able to modify it and save if they need to #ExtendedFunctionality)). I went further and provided a method to get a list of users associated with the provided ClaimPermission (useful for devs). Aka, win win for everyone (including devs) 🙂 

If you need more info let me know.

2020-03-28 15:45 UTC, RoboMWM commented
> This is not a quick fix. 

This is a quick fix, it's exposing an internal implementation, which if the plugin were not mature, this would be subject to change without notice.

2020-03-28 16:09 UTC, RoboMWM commented
Given the state of v16 though I may allow this through (with the setter removed, though). I first want to see if this can be fixed in the allowBuild checks or similar though.

2020-03-28 23:07 UTC, Jikoo commented
>I'd check to see if this can be fixed in the allowBuild checks or similar though first before resorting immediately all the way to here.

Would definitely be nice to have overloads for UUIDs or OfflinePlayers. I'd also really like to see it rewritten to not iterate over every entry several times, particularly not with repeat checks. I have a couple ideas, but I don't have time just yet to actually flesh them out fully.

2020-06-11 22:32 UTC, Jikoo commented
Addressed by #801

2020-06-11 22:32 UTC, closed without merging